# Generated by Django 3.1.7 on 2021-03-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
