# Generated by Django 3.1.7 on 2021-03-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0003_auto_20210324_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='Hospitals.department')),
            ],
        ),
    ]
