# Generated by Django 3.1.7 on 2021-03-26 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0005_auto_20210324_1138'),
        ('Rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveIntegerField()),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='Hospitals.doctor')),
            ],
        ),
    ]
